[package]
name = "koffee-tray"
version = "0.1.0"
authors = ["dpredovic <dpredovic@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
ksni = "0.1.3"
dbus = "0.9.2"
log = "0.4.14"
syslog = "5.0.0"
simple_logger = "1.11.0"
anyhow = "1.0.40"