[package]
name = "koffee-tray"
version = "0.1.3-dev"
authors = ["dpredovic <dpredovic@gmail.com>"]
edition = "2018"
build = "build.rs"
description = "A very lightweight Caffeine replacement, written in Rust"
homepage = "https://github.com/dpredovic/koffee-tray"
repository = "https://github.com/dpredovic/koffee-tray"
license = "GPL"
publish = false

[dependencies]
ksni = "0.1.3"
dbus = "0.9.2"
log = "0.4.14"
syslog = "5.0.0"
simple_logger = "1.11.0"
anyhow = "1.0.40"
rust-embed = { version = "5.9.0", features = ["interpolate-folder-path"] }

[build-dependencies]
image = "0.23.14"
bincode2 = "2.0.1"
serde = { version = "1.0.126", features = ["derive"] }
